version: '3'

services:
  hh:
    image:  hh-resume-updater:latest
    command: npm run start-updater
    restart: always
    volumes:
      - ./profiles:/app/profiles
      - ./src:/app/src
    ports:
      - "4000:4000"
    env_file:
        - ./.env

